compile:
	javac WhatsClient.java
run:
	java -Djgroups.bind_addr=127.0.0.1 -Djgroups.tcpping.initial_hosts=127.0.0.1[7800] WhatsClient arbitrary_group_name
clean:
	rm *.class
	rm *.history
view:
	cat *.history