all:
	@echo "Compiling .java files"
	javac *.java
	@echo "to run server:"
	@echo "rmiregistry &"
	@echo "java -Djava.security.policy=server.policy Server"
	@echo "to run client (another terminal):"
	@echo "java -Djava.security.policy=server.policy Client"